# Generated by Django 5.0.6 on 2024-08-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='building',
            field=models.ForeignKey(default=1, help_text='The building where the payment is made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.building', verbose_name='Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='flat',
            field=models.ForeignKey(default=1, help_text='The flat where the payment is made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.flat', verbose_name='Flat'),
            preserve_default=False,
        ),
    ]
