# Generated by Django 5.0.6 on 2024-08-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_payment_user_payment_building_payment_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Ödənişin məbləği', max_digits=10, verbose_name='Məbləğ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='building',
            field=models.ForeignKey(help_text='Ödəniş edilən bina', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.building', verbose_name='Bina'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(help_text='Ödənişin tarixi', verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='flat',
            field=models.ForeignKey(help_text='Ödəniş edilən mənzil', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.flat', verbose_name='Mənzil'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Ödəmə ilə əlaqəli xidmət (əgər varsa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.service', verbose_name='Xidmət'),
        ),
    ]
