# Generated by Django 5.0.6 on 2024-08-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_flat_user_user_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
