# Generated by Django 5.0.6 on 2024-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Əlavə edildi'), ('UPDATE', 'Dəyişdirildi'), ('DELETE', 'Silindi'), ('ACCESS', 'İcazə')], max_length=20),
        ),
    ]
