# Generated by Django 5.0.6 on 2024-08-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_log_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='users', to='buildings.branch'),
        ),
    ]
