# Generated by Django 5.0.6 on 2024-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_remove_user_branch_user_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='camera_url',
        ),
        migrations.AddField(
            model_name='branch',
            name='camera_urls',
            field=models.ManyToManyField(blank=True, related_name='branches', to='buildings.camera'),
        ),
    ]
