# Generated by Django 5.0.6 on 2024-08-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_camera_remove_branch_camera_url_branch_camera_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Camera'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='camera_urls',
        ),
        migrations.AddField(
            model_name='camera',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='buildings.branch'),
        ),
    ]
