# Generated by Django 5.0.6 on 2024-09-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_alter_camera_options_remove_branch_camera_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balans'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='is_rent',
            field=models.BooleanField(default=False, verbose_name='Icarə'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ad'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_document',
            field=models.FileField(upload_to='documents/', verbose_name='Sahibkar sənədi'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.section', verbose_name='blok'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='flats', to='buildings.service', verbose_name='Xidmətlər'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tenant_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Icarəçi sənədi'),
        ),
    ]
