# Generated by Django 5.0.6 on 2024-09-04 11:02

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_service_invoice_day_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='invoice_day',
            field=models.IntegerField(validators=[buildings.models.validate_day], verbose_name='Ödəniş günü'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Xidmətin adı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Qiymət'),
        ),
    ]
