# Generated by Django 5.0.6 on 2024-09-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_alter_service_invoice_day_alter_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='building',
        ),
        migrations.AddField(
            model_name='branch',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='commandant',
            field=models.ManyToManyField(blank=True, related_name='building', to=settings.AUTH_USER_MODEL, verbose_name='Komendant'),
        ),
        migrations.AddField(
            model_name='flat',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat', to=settings.AUTH_USER_MODEL),
        ),
    ]
