# Generated by Django 5.0.6 on 2024-09-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_remove_flat_user_remove_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-outcome_date'], 'verbose_name': 'Xərc', 'verbose_name_plural': 'Xərclər'},
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.building', verbose_name='Bina'),
        ),
    ]
