# Generated by Django 5.0.6 on 2024-09-24 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0029_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon nömrəsi aşağıdakı formatda daxil edilməlidir: '+994xxxxxxxxx'.", regex='^\\+994\\d{9}$')]),
        ),
    ]
