# Generated by Django 5.0.6 on 2024-09-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0030_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
