# Generated by Django 5.0.6 on 2024-09-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0034_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Borc', 'verbose_name_plural': 'Borclar'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buildings.charge', verbose_name='Borc'),
        ),
    ]
