# Generated by Django 5.0.6 on 2024-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0035_alter_charge_options_remove_payment_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Kamera linki'),
        ),
    ]
