# Generated by Django 5.0.6 on 2024-10-11 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0037_news_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plate', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('car_plates', models.ManyToManyField(blank=True, related_name='garrage', to='buildings.carplate', verbose_name='Maşın nömrəsi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garrage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
