# Generated by Django 5.0.6 on 2024-10-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0038_carplate_garrage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garrage',
            new_name='Garage',
        ),
    ]
