# Generated by Django 5.0.6 on 2024-10-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0040_alter_carplate_options_alter_garage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='car_plates',
        ),
        migrations.AddField(
            model_name='carplate',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buildings.garage'),
            preserve_default=False,
        ),
    ]
